title: My Page
email: marius dot rockschies (at) travedsl dot de
author: marius
copyright: Marius 2020
linkedin_username: marius-rockschies-b4254516b
description: Feel free to contact me for whatever reason.
theme: minima
# youtube_username: wfefwe
# github_username: fwewe
# twitter_username: fwee
